### ISSUE TITLE
PIGS for 1 dimensional  quantum harmonic oscillator  

### ISSUE THREAD

**Issue by theonov13** [DelMaestroGroup/pimc#1]
Dear authors, community, 

I compiled the PIGS code for 1d. 
I want to use the code to calculate 
the ground state energy of a particle trapped in a box, i.e., 
calculating the [quantum harmonic oscillator](https://en.wikipedia.org/wiki/Quantum_harmonic_oscillator). 

I played around with the parameters. 
However, I failed to get the correct answer E = 0.5 +- error E_h.   

My current set of parameters. 
```bash 
PATH=~/Programms/DelMaestroGroup/pimc/build
$PATH/pigs.e --canonical --action "primitive" -t 0.01 -N 1 -L 1  -P 20 -m 0.00055 -E 1 -S 20 -I harmonic -X harmonic --wavefunction "sech" --estimator "energy"
```

I would be glad for any help. 

Have a nice day, 
Sebastian

**Comment by agdelma** [comment]
Hi Sebastian,

Sorry for my delayed reply on this.  The issue is in the mass parameter and the default units that the code uses which were originally setup for simulating helium.  Try the following slight modification of your command line string:

```bash
$PATH/pigs.e -m 48.48 -L 20 -N 1 -M 8 -t 0.4 -P 20 -E 100000 -S 1000 --bin_size=1000 -I free -X harmonic -l 20
```

This is for a single simple harmonic oscillator and using pimcave.py yields
```bash
# Number Samples   1000
K                    0.25040	     0.00073	 0.29
V                    0.24990	     0.00025	 0.10
V_ext                0.24993	     0.00025	 0.10
V_int                0.00000	     0.00000	 0.00
E                    0.50031	     0.00070	 0.14
E_mu                 0.50031	     0.00070	 0.14
K/N                  0.25040	     0.00073	 0.29
V/N                  0.24990	     0.00025	 0.10
E/N                  0.50031	     0.00070	 0.14
us                  60.72779	     0.20453	 0.34
mcsteps           1000.00000	     0.00000	 0.00
```

Here mass units are set by the fact that we measure the thermal de broglie wavelength in units of $Å^2 K$, i.e. $\lambda = \hbar^2/(2 m k_B) = 24.24 / m$ thus setting `m=48.48` on the command line above is equivalent to setting $m = 1$ in the SHO.   This is a bit cumbersome, I appreciate! Please reach out via email if you would like to discuss further.

**Comment by theonov13** [comment]
Hi, 

thank you for your answer.
 
The pigs command line you send runs without problems.
And the results now look physical. 
However, for python3.10, 
I'm not able to get the Python post-processing tools installed. 

I'm curious about the definition of the thermal de Broglie wavelength you gave.
It looks like you use this definition also in other projects, i.e.,  [1](https://github.com/agdelma/pimc-notes/blob/master/Code/sho-pimc.py#LL178C31-L178C31).
 
However, I think the thermal de Broglie wavelength is given by 

$\lambda_{\varepsilon} = \frac{2\pi \hbar}{\sqrt{2\pi m k_{\mathrm{B}} T_{\varepsilon}}}$. 

It would be nice if you can comment on this, 
if you find some time. 

Best, 
Sebastian

**Comment by agdelma** [comment]
Thanks for the followup/correction. Yes, you are correct of course, this is just bad/sloppy nomenclature that snuck into the code at some point.  You have the correct definition.  Basically we measure energies in Kelvin, so you could think of writing the dimensionless free Hamiltonian as:

$-\beta H_0 = 4 \pi \lambda_{\epsilon}^2 \sum_i \nabla_i^2 = \frac{\lambda}{T} \sum_i \nabla_i^2$

using the definition of $\lambda$ and $\lambda_{\epsilon}$ used above. 

I haven't tested [pimcscripts](https://github.com/delmaestrogroup/pimcscripts) beyond python3.9.  Can you submit an issue with the error? I can create a 3.10 environment and try to figure out what is going on.

**Comment by theonov13** [comment]
Thank you for the detailed answer. 
I made some pen and paper work and the choice of $\lambda$ seems not to be a problem. 
However, I have some other questions being not suited to this issue. 

```bash 
~$ lsb_release -a

Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

~$ python3 --version 
Python 3.10.6

~$ python3 setup.py install --user
"[...] SetuptoolsDeprecationWarning [...]"

~$ pip3 install -e .
"[...] python setup.py develop did not run successfully. [...]"
```

I assume the errors are related to the old way of installing the code. 
Python changed its way to handle meta-data. 
In principle, I think you need a [pyproject.toml](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/) file 
to handle the meta-data and get the installation using setuptools 
running again.

**Comment by theonov13** [comment]
I set up a ```pyproject.toml``` file for pimcscripts at the same depth as setup.py. 

*pyproject.toml*
```bash 
[build-system]
requires = ["setuptools>=1.2"]
build-backend = "setuptools.build_meta"
``` 

Utilizing this the code compiles for me. 

```bash 
~$ python3.10 -m pip install -e .
```
